### ISSUE TITLE
Add self to team page: COGG-183

### ISSUE THREAD

**Issue by ljdursi** [CanDIG/candig.github.io#28]
Submit a pull request with a square jpg representing you (a photo, or an avatar of some sort; recommended resolution 1280x1280) in `img/team` and adding your info to `_data/team.yml` in this repo - that’ll show up (after a little delay) on https://www.distributedgenomics.ca/team.html .

You can copy any technical team member in `_data/team.yml` as a template and just change name, image name, etc.

There's no order to the people in `_data/team.yml` except that we try to keep it in four sections: current technical team members (team: technical), the PIs (team: leadership), and students, etc. who have moved on (team: recent_alumni and then eventually team: alumni).

**Comment by ljdursi** [comment]
Ping!

**Comment by amanjeev** [comment]
This is done
